name: Continuous Integration

# Note: This workflow is designed to handle missing secrets gracefully.
# Optional integrations (Codecov, Lighthouse CI, Snyk) will be skipped if tokens are not configured.

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '20.x'

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: false
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run type checking
      run: npm run type-check
      
    - name: Run linting
      run: npm run lint
      
    - name: Run unit tests
      run: npm run test:coverage
      
    # Upload to Codecov (gracefully handles missing token)
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      continue-on-error: true
      with:
        file: ./coverage/lcov.info
        flags: unittests
        name: codecov-${{ matrix.node-version }}
        fail_ci_if_error: false
        
    # Always upload coverage as artifacts
    - name: Upload coverage artifacts
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report-${{ matrix.node-version }}
        path: coverage/
        retention-days: 7
        
  # Temporarily disabled E2E tests due to CI timeout issues
  # e2e-tests:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4
  #     
  #   - name: Setup Node.js
  #     uses: actions/setup-node@v4
  #     with:
  #       node-version: '20.x'
  #       cache: 'npm'
  #       
  #   - name: Install dependencies
  #     run: npm ci
  #     
  #   - name: Install Playwright browsers
  #     run: npx playwright install --with-deps
  #     
  #   - name: Run Playwright tests
  #     run: npm run test:e2e
  #     
  #   - name: Upload Playwright report
  #     uses: actions/upload-artifact@v4
  #     if: always()
  #     with:
  #       name: playwright-report
  #       path: playwright-report/
  #       retention-days: 30
        
  lighthouse:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: false
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      
    - name: Start server
      run: npm start &
      
    - name: Wait for server
      run: npx wait-on http://localhost:3000 --timeout 60000
      
    # Install Lighthouse tools
    - name: Install Lighthouse tools
      run: |
        npm install -g lighthouse
        npm install -g @lhci/cli@0.12.x
      
    # Run basic Lighthouse audit (always works)
    - name: Run Lighthouse audit
      continue-on-error: true
      run: |
        lighthouse http://localhost:3000 --output html --output-path ./lighthouse-report.html
        echo "Basic Lighthouse audit completed"
        
    - name: Upload Lighthouse report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: lighthouse-report
        path: lighthouse-report.html
        retention-days: 30
        
  security:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: false
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run security audit
      run: npm audit --audit-level=moderate
      
    # Run enhanced security audit
    - name: Run enhanced security audit
      continue-on-error: true
      run: |
        echo "Running enhanced npm security audit"
        npm audit --audit-level=high || echo "High-level vulnerabilities found, check manually"
        
  build:
    runs-on: ubuntu-latest
    needs: [test] # Removed e2e-tests dependency
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: false
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: .next/
        retention-days: 1 